### ISSUE TITLE
hooks?

### ISSUE THREAD

**Issue by bebbi** [molindo/react-apollo-network-status#12]
Hey! Would it be a lot of effort to add hooks?

**Comment by amannn** [comment]
Hi @bebbi! Funny that you're asking, I'm actually in progress of an overhaul which would also bring hooks support. My local tests work, but I haven't tried it out in a real app yet though.

Are you interested in trying out an alpha version? Would also be good to get feedback for the API.

**Comment by bebbi** [comment]
@amannn Haha, as if my start-up wasn't in deep enough trouble already.. Yes, happy to take the bait 👍 I'm only using it in the base config right now though.

**Comment by amannn** [comment]
@bebbi Ha, nice 😄.

Ok, here we go:

```
yarn add react-apollo-network-status@2.0.0-alpha.1
```

You can have a look at [the updated README](https://github.com/molindo/react-apollo-network-status/blob/2.0/README.md) for usage instructions.

Let me know how it goes!

**Comment by bebbi** [comment]
I fully removed the old link and notifier component.

I added the new one as such:

```
import { ApolloNetworkStatusProvider } from 'react-apollo-network-status'
...
ReactDOM.render(
      <ApolloProvider client={client}>
        <ApolloHooksProvider client={client}>
          <ApolloNetworkStatusProvider>
            <App />
          </ApolloNetworkStatusProvider>
        </ApolloHooksProvider>
      </ApolloProvider>,
  document.getElementById('root')
)
```

and using the hook in the component with

```
import { useApolloNetworkStatus } from 'react-apollo-network-status'
```

and I'm getting the error

![image](https://user-images.githubusercontent.com/2752391/57817572-34fc9b00-7780-11e9-9dec-e1f31d68d82b.png)

Any ideas? Btw I'm using `apollo-boost` for `ApolloLink`.

**Comment by amannn** [comment]
Hmm, looks like an issue with the bundler.  There's now also a `.mjs` file published for bundlers which support this. What bundler are you using? Any chance that there is something misconfigured? Maybe I shouldn't publish the ES module build if this can cause trouble.

I've created a code sandbox which uses CRA and it works there: https://codesandbox.io/embed/reactapollonetworkstatus-r3g76.

You can try to import from `react-apollo-network-status/dist/index.js` or `react-apollo-network-status/dist/index.umd.js` though if you don't want modern ES modules.

**Comment by bebbi** [comment]
Hm. Sorry I forgot to mention, I was using it with `create-react-app@2.1.5`.

**Comment by bebbi** [comment]
@amannn Once I made some other changes I'll try to bump `react-scripts` and see if that changes anything.
You're probably more familiar with [mjs issues](https://github.com/facebook/create-react-app/issues/5234) than I am, but that issue does look somewhat related.

**Comment by amannn** [comment]
Ok, I see. Maybe older versions of CRA have issues with `.mjs`. Otherwise you can try the CommonJS or UMD build in the meantime.

**Comment by bebbi** [comment]
no, I've tried with `3.0.1` and get the identical error. I think it's a `mjs` issue.
Importing from `dist/index.js` works.

However, while I'm now getting a `numPendingQueries`, it's always `0`.

FYI imports:
```
import { ApolloNetworkStatusProvider } from 'react-apollo-network-status/dist/index.js'
```

and

```
import { useApolloNetworkStatus } from 'react-apollo-network-status/dist/index.js'
```

**Comment by amannn** [comment]
Hm, interesting that it works in CodeSanbox though. I've just published `react-apollo-network-status@2.0.0-alpha.2` which uses the CommonJS build as the default, so you should be able to remove the `/dist/index.js` from your imports.

About the queries not being registered: You're using `react-apollo-hooks`, right? The issue with that library is that they're exposing their own context, however this library only considers the official context from `react-apollo`. There is some [discussion about using the official context](https://github.com/trojanowski/react-apollo-hooks/issues/131) and also [Apollo will likely provide official hooks soon](https://twitter.com/peggyrayzis/status/1128280687470100480), so I think supporting `react-apollo-hooks` is out of scope for this library.

However, you can add a small workaround in the meantime as shown in [the latest version of my CodeSandbox demo](https://codesandbox.io/s/reactapollonetworkstatus-r3g76?from-embed).

Hope that helps. Let me know if this works for you!

**Comment by bebbi** [comment]
this works 💯

**Comment by amannn** [comment]
Cool, great to hear 👍. Let me know if you have any feedback. I'll test it in 2 apps of mine as well and then I'll probably release the stable version.

**Comment by bebbi** [comment]
So far this is working nicely...
