### ISSUE TITLE
Export the OperationError type

### ISSUE THREAD

**Issue by zamiang** [molindo/react-apollo-network-status#14]
Exporting https://github.com/molindo/react-apollo-network-status/blob/e08e7b43e2e3447ec0d9399262d17b162162805e/src/useApolloNetworkStatus.ts#L44 would be very useful for creating an error handling component. Currently I copy-pasted this type into my codebase which isn't ideal.

**Comment by amannn** [comment]
Thanks for raising this!

Shouldn't this type be inferred for the call site? In VSCode I see this, although it's taken from a JS codebase:

<img width="935" alt="Screenshot 2019-06-03 at 08 27 17" src="https://user-images.githubusercontent.com/4038316/58780575-a25e5780-85d9-11e9-97b2-a1537d9931d4.png">

From my understanding you should be able to get type checking without having to explicitly define the type. I'm fairly new to TypeScript though, so I might be wrong.

Or do you need the type to pass this data structure to a function? Can you share a bit more context?

**Comment by zamiang** [comment]
Yup! 

I do have access to it when directly handling the response, but am creating a shared component which handles parsing / rendering errors. Currently it handles the ApolloError type and would like it to also handle the OperationError type here. Given that it is a separate component, it would be helpful to directly import the type from this library.

**Comment by amannn** [comment]
Alright, that makes sense to me. Would you like to make a PR?
