### ISSUE TITLE
Error: may not update existing query string in store

### ISSUE THREAD

**Issue by dizzyn** [molindo/react-apollo-network-status#22]
Getting the bug using:

"react-apollo": "^3.1.3",
"react-apollo-network-status": "^3.0.0",
"apollo-client": "^2.6.8",
"apollo-server-micro": "^2.9.16",

The error:
![image](https://user-images.githubusercontent.com/2071816/72681918-81933580-3ac8-11ea-84ab-0cb00005a5e4.png)

Thank You

**Comment by amannn** [comment]
Thanks for the report! Can you share a reproduction of the error with https://codesandbox.io/ please?

The error is thrown from Apollo, it's hard to know wether it's related to this library.

**Comment by dizzyn** [comment]
I can not - it is complex Next.js project. I understand that it is hard to reproduce.

This is definitely related because i can get rid of the bug by removing the react-apollo-network-status.

Sorry

**Comment by markrzen** [comment]
I am also seeing this. I only see it when webpack is hotswapping changes.

**Comment by gouegd** [comment]
I had that issue too, getting rid of react-apollo-network-status was a fix I could live with.
For me it happened whenever I chained a query to a successful mutation.

**Comment by amannn** [comment]
@gouegd There's a new alpha version out that should fix this:

```
react-apollo-network-status@4.0.0-alpha.1
```

Note that there is a breaking change, please see https://github.com/molindo/react-apollo-network-status/pull/29.
