### ISSUE TITLE
Support apollo client 3

### ISSUE THREAD

**Issue by freshollie** [molindo/react-apollo-network-status#25]
Hey,

Seems it's a breaking change to use this with `@apollo/client@3` because apollo client 3 bundles the context and provider into a different package, and I guess the context name has changed. Not sure if it would be possible to make this backwards compatible.

```
Uncaught Error: `ApolloNetworkStatusProvider` needs to be placed below `ApolloProvider`.
```

**Comment by amannn** [comment]
Thanks for the report!

In the past I always made a breaking change when we had to support a new provider since I don't know of a good way of supporting different contexts without bloating the bundle unnecessarily. I'll wait for the final release of Apollo Client 3 for now, I hope that's ok for you.

If you need to make it work for the time being, I guess you could still use v1.1 of this library, as it is not bound to a specific context. Note that the [API was a bit different back then](https://github.com/molindo/react-apollo-network-status/tree/583a00f6344e05edcfee90bee0823a7736f56021).

**Comment by freshollie** [comment]
That's fine. For now I am using the old `ApolloProvider` with the new apollo client, which still works.

**Comment by darrikonn** [comment]
@amannn any news on this?
I'm using `@apollo/client` and getting the same error message:
```
Uncaught Error: `ApolloNetworkStatusProvider` needs to be placed below `ApolloProvider`.
```

**Comment by amannn** [comment]
I've created a WIP pull request that tracks the support of Apollo Client 3 for this library: https://github.com/molindo/react-apollo-network-status/pull/30/. I'm waiting for the official release of Apollo Client 3 before we can merge that though.

There's an alpha release of this library that you can use to test this in your apps that use `@apollo/client`. Note that the PR is based on [a breaking change](https://github.com/molindo/react-apollo-network-status/pull/29) that I want to merge before we can support Apollo Client 3.

Here you can find more information about how to upgrade:
 - [Upcoming changelog](https://github.com/molindo/react-apollo-network-status/blob/support-apollo-client-3/CHANGELOG.md)
- [Upcoming readme](https://github.com/molindo/react-apollo-network-status/tree/support-apollo-client-3)

It would be very helpful if you can provide feedback if everything works in your app with the new version! Thank you!

**Comment by erosval** [comment]
In the next version is it possible to have "@apollo/client" as a peer dependency?
With the new Apollo client, only one import is needed and all projects must have it as a dependency.

**Comment by ajnatural** [comment]
Hey, thanks so much for making this library - I've found it incredibly useful!

Apollo 3.0 has been released now, do you have any updates on this issue? I've tried the alpha release posted above, but am getting this TS error:

```
ERROR in [at-loader] ./resources/js/app.tsx:87:15
    TS2322: Type 'ApolloLinkNetworkStatus' is not assignable to type 'ApolloLink | RequestHandler'.
  Type 'ApolloLinkNetworkStatus' is not assignable to type 'ApolloLink'.
    Types of property 'split' are incompatible.
      Type '(test: (op: import("/Users/ajain/git/elenta/node_modules/react-apollo-network-status/node_modules/@apollo/client/link/core/types").Operation) => boolean, left: import("/Users/ajain/git/elenta/node_modules/react-apollo-network-status/node_modules/@apollo/client/link/core/ApolloLink").ApolloLink | import("/Users/ajain...' is not assignable to type '(test: (op: import("/Users/ajain/git/elenta/node_modules/@apollo/client/link/core/types").Operation) => boolean, left: import("/Users/ajain/git/elenta/node_modules/@apollo/client/link/core/ApolloLink").ApolloLink | import("/Users/ajain/git/elenta/node_modules/@apollo/client/link/core/types").RequestHandler, right?: ...'.
        Types of parameters 'left' and 'left' are incompatible.
          Type 'import("/Users/ajain/git/elenta/node_modules/@apollo/client/link/core/ApolloLink").ApolloLink | import("/Users/ajain/git/elenta/node_modules/@apollo/client/link/core/types").RequestHandler' is not assignable to type 'import("/Users/ajain/git/elenta/node_modules/react-apollo-network-status/node_modules/@apollo/client/link/core/ApolloLink").ApolloLink | import("/Users/ajain/git/elenta/node_modules/react-apollo-network-status/node_modules/@apollo/client/link/core/types").RequestHandler'.
            Type 'ApolloLink' is not assignable to type 'ApolloLink | RequestHandler'.
              Type 'import("/Users/ajain/git/elenta/node_modules/@apollo/client/link/core/ApolloLink").ApolloLink' is not assignable to type 'import("/Users/ajain/git/elenta/node_modules/react-apollo-network-status/node_modules/@apollo/client/link/core/ApolloLink").ApolloLink'.
                Types of property 'split' are incompatible.
                  Type '(test: (op: import("/Users/ajain/git/elenta/node_modules/@apollo/client/link/core/types").Operation) => boolean, left: import("/Users/ajain/git/elenta/node_modules/@apollo/client/link/core/ApolloLink").ApolloLink | import("/Users/ajain/git/elenta/node_modules/@apollo/client/link/core/types").RequestHandler, right?: ...' is not assignable to type '(test: (op: import("/Users/ajain/git/elenta/node_modules/react-apollo-network-status/node_modules/@apollo/client/link/core/types").Operation) => boolean, left: import("/Users/ajain/git/elenta/node_modules/react-apollo-network-status/node_modules/@apollo/client/link/core/ApolloLink").ApolloLink | import("/Users/ajain...'.
                    Types of parameters 'left' and 'left' are incompatible.
                      Type 'import("/Users/ajain/git/elenta/node_modules/react-apollo-network-status/node_modules/@apollo/client/link/core/ApolloLink").ApolloLink | import("/Users/ajain/git/elenta/node_modules/react-apollo-network-status/node_modules/@apollo/client/link/core/types").RequestHandler' is not assignable to type 'import("/Users/ajain/git/elenta/node_modules/@apollo/client/link/core/ApolloLink").ApolloLink | import("/Users/ajain/git/elenta/node_modules/@apollo/client/link/core/types").RequestHandler'.
                        Type 'ApolloLink' is not assignable to type 'ApolloLink | RequestHandler'.
                          Type 'import("/Users/ajain/git/elenta/node_modules/react-apollo-network-status/node_modules/@apollo/client/link/core/ApolloLink").ApolloLink' is not assignable to type 'import("/Users/ajain/git/elenta/node_modules/@apollo/client/link/core/ApolloLink").ApolloLink'.
                            Types of property 'split' are incompatible.
                              Type '(test: (op: import("/Users/ajain/git/elenta/node_modules/react-apollo-network-status/node_modules/@apollo/client/link/core/types").Operation) => boolean, left: import("/Users/ajain/git/elenta/node_modules/react-apollo-network-status/node_modules/@apollo/client/link/core/ApolloLink").ApolloLink | import("/Users/ajain...' is not assignable to type '(test: (op: import("/Users/ajain/git/elenta/node_modules/@apollo/client/link/core/types").Operation) => boolean, left: import("/Users/ajain/git/elenta/node_modules/@apollo/client/link/core/ApolloLink").ApolloLink | import("/Users/ajain/git/elenta/node_modules/@apollo/client/link/core/types").RequestHandler, right?: ...'.
                                Types of parameters 'left' and 'left' are incompatible.
                                  Type 'import("/Users/ajain/git/elenta/node_modules/@apollo/client/link/core/ApolloLink").ApolloLink | import("/Users/ajain/git/elenta/node_modules/@apollo/client/link/core/types").RequestHandler' is not assignable to type 'import("/Users/ajain/git/elenta/node_modules/react-apollo-network-status/node_modules/@apollo/client/link/core/ApolloLink").ApolloLink | import("/Users/ajain/git/elenta/node_modules/react-apollo-network-status/node_modules/@apollo/client/link/core/types").RequestHandler'.
                                    Type 'ApolloLink' is not assignable to type 'ApolloLink | RequestHandler'.
```

**Comment by amannn** [comment]
I recently looked into finishing the Apollo Client 3 support and also noticed this error. I'll keep you posted once I have something working! 🙂

**Comment by amannn** [comment]
I've just published a new beta version with the latest compatibility fixes in place: 

```
react-apollo-network-status@5.0.0-beta.1
```

I think it works with the new `@apollo/client`, at least my local tests in this repository work fine. I currently don't have any production apps that use `@apollo/client`. If some of you could help me to test this release, this would be super helpful!

If you find any issues, feel free to comment on the corresponding PR: https://github.com/molindo/react-apollo-network-status/pull/30.

**Comment by luuksommers** [comment]
Can confirm it's also working in our application! Thanks you!

**Comment by erosval** [comment]
I also confirm that it works but please consider to move "@apollo/client" as a peer dependency. Tks
