### ISSUE TITLE
status.queryError and status.mutationError are aways undefined 

### ISSUE THREAD

**Issue by millerox** [molindo/react-apollo-network-status#27]
Hello, 
The package seems to be the perfect fir for my case, but I cant make it working 

 const status = useApolloNetworkStatus()
 const error = status.queryError || status.mutationError

When query or mutation error happens,  status.queryError || status.mutationError objects  stay undefined. numPendingQueries, numPendingMutations are always 0

The currents versions:
   "react-apollo": "^2.5.8",
    "react-apollo-network-status": "^2.0.0",

Do you have any suggestions where I should look at  ?
Thanks

**Comment by amannn** [comment]
Hmm, the 2.x version of `react-apollo` should be compatible with `react-apollo-network-status@^2.x`. If there are issues though, you could try upgrading to the 3.x version of both packages (see [changelog](https://github.com/molindo/react-apollo-network-status/blob/master/CHANGELOG.md)).

**Comment by millerox** [comment]
The latest versions worked  perfectly. (not sure what exactly was incompatible before) Thanks for the package!
We gonna wait until Apollo3 final release to implement it in the project. We use mobx to manage errors globally till then

**Comment by amannn** [comment]
Alright then!

Btw. react-apollo@3.x is already stable, it's just Apollo Client where the 3.x version is currently being developed.
