### ISSUE TITLE
Listener isn't removed after a component is unmounted and is still receiving prop/state updates.

### ISSUE THREAD

**Issue by philipthemagnificent** [molindo/react-apollo-network-status#3]
New to pull requesting, and not sure of the right workflow.  Anyways, here is a link to the pull request with the fix. 

https://github.com/molindo/react-apollo-network-status/pull/2

**Comment by philipthemagnificent** [comment]
New to pull requesting, maybe this isn't the best workflow, but I'm not sure of another way,  Anyways here is a link to the pull request the with fix.

https://github.com/molindo/react-apollo-network-status/pull/2

**Comment by amannn** [comment]
Thanks for the PR! This is released in [0.0.2](https://github.com/molindo/react-apollo-network-status/releases/tag/0.0.2).
